version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: 
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD= ${DATABASE_PASSWORD}
      - MYSQL_DATABASE= ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT_DOCKER}
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure   
    env_file: 
      - ./.env
    ports: 
      - ${STRAPI_PORT}:${STRAPI_PORT}
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      HOST: ${HOST}
      STRAPI_PORT: ${STRAPI_PORT}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    stdin_open: true
    tty: true

volumes:
  db: